version: '3'

services:
  client1:
    build:
      context: ./
      dockerfile: ./RandomForest/client/Dockerfile
    ports:
      - "5001:5000"
    command: flask run --port 5000 --host 0.0.0.0
    volumes:
      - .:/code

  client2:
    build:
      context: ./
      dockerfile: ./RandomForest/client/Dockerfile
    ports:
      - "5002:5000"
    command: flask run --port 5000 --host 0.0.0.0
    volumes:
      - .:/code

  client3:
    build:
      context: ./
      dockerfile: ./RandomForest/client/Dockerfile
    ports:
      - "5003:5000"
    command: flask run --port 5000 --host 0.0.0.0
    volumes:
      - .:/code

  client4:
    build:
      context: ./
      dockerfile: ./RandomForest/client/Dockerfile
    ports:
      - "5004:5000"
    command: flask run --port 5000 --host 0.0.0.0
    volumes:
      - .:/code